name: assignment-test
<<<<<<< HEAD
on: 
=======
on:
>>>>>>> buildroot-assignments-base/master
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
<<<<<<< HEAD
    unit-test:
        container: cuaesd/aesd-autotest:unit-test
        runs-on: self-hosted
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run : git submodule update --init --recursive
          - name: Run unit test
            run: ./unit-test.sh
=======
    full-test:
        container: cuaesd/aesd-autotest:assignment4-buildroot
        runs-on: self-hosted
        timeout-minutes: 120
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run: git submodule update --init --recursive
          - uses: webfactory/ssh-agent@v0.5.3
            with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          - name: Run full test
            env:
              GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
            run: ./full-test.sh
          - name: Cleanup
            if: always()
            run: |
              ssh-add -D
>>>>>>> buildroot-assignments-base/master
